---
version: "2.1"
services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${USER}
      - PASS=${PASS}
    volumes:
      - /mnt/usb/apps/transmission/config:/config
      - ${DOWNLOAD_DIR}:/downloads
      - /mnt/usb/apps/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
