name: Transmission Torrent Client
maintainer: count-null
description: Download and seed torrents directly from your device
links:
  - label: GitHub
    url: https://github.com/Secretmapper/combustion
open_link: ":9091"
var_fields:
  - name: USER
    label: Username
    field: input
    default: drop
  - name: PASS
    label: Password
    field: input
    default: drop
  - name: DOWNLOAD_DIR
    label: Download Directory
    field: input
    default: "/mnt/usb/files/transmission/torrents/"
